// Programación de RONALDO BALLESTEROS extraída del cronograma "1. 3536507 - ANALISIS Y DESARROLLO SOFTWARE (12).xlsx" (22/09/2026).
// Se carga con el botón "Cargar programación incluida" de la pestaña Programación.
window.PROGRAMACION_PRECARGADA = [
 {
  "id": "prog001",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Establecer requisitos de la solución de software de acuerdo con estándares y procedimiento técnico",
  "rap": "",
  "ambiente": "",
  "date": "2026-09-15",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog002",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Establecer requisitos de la solución de software de acuerdo con estándares y procedimiento técnico",
  "rap": "",
  "ambiente": "",
  "date": "2026-09-18",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog003",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-09-21",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog004",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-09-24",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog005",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-09-25",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog006",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-09-26",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog007",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-02",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog008",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-05",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog009",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-07",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog010",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-08",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog011",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-09",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog012",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-13",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog013",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-16",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog014",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-17",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog015",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-21",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog016",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-22",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog017",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-23",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog018",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-24",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog019",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-29",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog020",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-10-31",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog021",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-05",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog022",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-06",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog023",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-07",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog024",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-10",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog025",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-11",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog026",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-12",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog027",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-13",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog028",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-17",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog029",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-19",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog030",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-20",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog031",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-21",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog032",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-23",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog033",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-24",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog034",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Diseñar la solución de software de acuerdo con procedimientos y requisitos técnico",
  "rap": "EVALUAR RAP 01-02 Y 03",
  "ambiente": "",
  "date": "2026-11-25",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog035",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Estructurar propuesta técnica de servicio de tecnología de la información según requisitos técnicos y normativa",
  "rap": "RAP 01 DEFINIR ESPECIFICACIONES TÉCNICAS DEL SOFTWARE DE ACUERDO CON LAS CARACTERÍSTICAS DEL SOFTWARE A CONSTRUIR",
  "ambiente": "",
  "date": "2026-11-26",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog036",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Estructurar propuesta técnica de servicio de tecnología de la información según requisitos técnicos y normativa",
  "rap": "RAP 01 DEFINIR ESPECIFICACIONES TÉCNICAS DEL SOFTWARE DE ACUERDO CON LAS CARACTERÍSTICAS DEL SOFTWARE A CONSTRUIR",
  "ambiente": "",
  "date": "2026-11-27",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog037",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Estructurar propuesta técnica de servicio de tecnología de la información según requisitos técnicos y normativa",
  "rap": "RAP 01 DEFINIR ESPECIFICACIONES TÉCNICAS DEL SOFTWARE DE ACUERDO CON LAS CARACTERÍSTICAS DEL SOFTWARE A CONSTRUIR",
  "ambiente": "",
  "date": "2026-12-01",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog038",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Estructurar propuesta técnica de servicio de tecnología de la información según requisitos técnicos y normativa",
  "rap": "RAP 01 DEFINIR ESPECIFICACIONES TÉCNICAS DEL SOFTWARE DE ACUERDO CON LAS CARACTERÍSTICAS DEL SOFTWARE A CONSTRUIR",
  "ambiente": "",
  "date": "2026-12-02",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog039",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "Estructurar propuesta técnica de servicio de tecnología de la información según requisitos técnicos y normativa",
  "rap": "RAP 01 DEFINIR ESPECIFICACIONES TÉCNICAS DEL SOFTWARE DE ACUERDO CON LAS CARACTERÍSTICAS DEL SOFTWARE A CONSTRUIR",
  "ambiente": "",
  "date": "2026-12-03",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog040",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "DESARROLLAR LA SOLUCIÓN DE SOFTWARE DE ACUERDO CON EL DISEÑO Y METODOLOGÍAS DE DESARROLLO",
  "rap": "",
  "ambiente": "",
  "date": "2026-12-04",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog041",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "DESARROLLAR LA SOLUCIÓN DE SOFTWARE DE ACUERDO CON EL DISEÑO Y METODOLOGÍAS DE DESARROLLO",
  "rap": "",
  "ambiente": "",
  "date": "2026-12-09",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog042",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "DESARROLLAR LA SOLUCIÓN DE SOFTWARE DE ACUERDO CON EL DISEÑO Y METODOLOGÍAS DE DESARROLLO",
  "rap": "",
  "ambiente": "",
  "date": "2026-12-10",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog043",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "DESARROLLAR LA SOLUCIÓN DE SOFTWARE DE ACUERDO CON EL DISEÑO Y METODOLOGÍAS DE DESARROLLO",
  "rap": "",
  "ambiente": "",
  "date": "2026-12-11",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog044",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "DESARROLLAR LA SOLUCIÓN DE SOFTWARE DE ACUERDO CON EL DISEÑO Y METODOLOGÍAS DE DESARROLLO",
  "rap": "",
  "ambiente": "",
  "date": "2026-12-12",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog045",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "DESARROLLAR LA SOLUCIÓN DE SOFTWARE DE ACUERDO CON EL DISEÑO Y METODOLOGÍAS DE DESARROLLO",
  "rap": "",
  "ambiente": "",
  "date": "2026-12-14",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog046",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "DESARROLLAR LA SOLUCIÓN DE SOFTWARE DE ACUERDO CON EL DISEÑO Y METODOLOGÍAS DE DESARROLLO",
  "rap": "",
  "ambiente": "",
  "date": "2026-12-15",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 },
 {
  "id": "prog047",
  "status": "pendiente",
  "activity": "formacion",
  "ficha": "3536507",
  "competencia": "DESARROLLAR LA SOLUCIÓN DE SOFTWARE DE ACUERDO CON EL DISEÑO Y METODOLOGÍAS DE DESARROLLO",
  "rap": "",
  "ambiente": "",
  "date": "2026-12-16",
  "start": "12:00",
  "end": "20:00",
  "hours": 8
 }
];
